[package]
name = "terminal_manager"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(windows)'.dependencies.winapi]
winapi = "0.3.9"
features = ["consoleapi", "errhandlingapi", "handleapi", "processenv", "winbase", "winuser"]

[target.'cfg(unix)'.dependencies]