[package]
name = "terminal_manager"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(windows)'.dependencies.winapi]
winapi = "0.3.9"
features = ["consoleapi", "processenv", "winbase"]

[target.'cfg(unix)'.dependencies]